apiVersion: v1
kind: Service
metadta:
  name: usermgmt-restapp-service
spec:
  type: NodePort
  selector:
    app: usermgmt-restapp
  ports:
    - port: 8095
      targetPort: 8095
      nodePort: 31231